name: Go

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Go build, test, & vet
      run: |
        go build -o ./cmd/firefly.go firefly
        go test ./...
        go vet ./...
      working-directory: .
